"""add chat history tables

Revision ID: 6e022f24008d
Revises: 
Create Date: 2026-02-24 21:48:36.232553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '6e022f24008d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False, schema='ai')
    op.create_table('post_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_post_embeddings_post_id'), 'post_embeddings', ['post_id'], unique=False, schema='ai')
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai.chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='chat_messages', schema='ai')
    op.drop_table('chat_messages', schema='ai')
    op.drop_index(op.f('ix_ai_post_embeddings_post_id'), table_name='post_embeddings', schema='ai')
    op.drop_table('post_embeddings', schema='ai')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='chat_sessions', schema='ai')
    op.drop_table('chat_sessions', schema='ai')
    # ### end Alembic commands ###
